// pokedex-react/src/pages/Homepage/index.tsx
import { useEffect, useState } from "react";
import { PokemonCard } from "../../Components/PokemonCard";
import { Container, ContentContainer, Title } from "./styles";
import { DeletePokemon, FetchPokemons } from "../../services/PokemonService";
import { useNavigate } from "react-router-dom";

type Pokemon = {
  id: string;
  name: string;
  description: string;
  type: string;
};
export const Homepage = () => {
  const [pokemons, setPokemons] = useState<Pokemon[]>([]);
  const navigate = useNavigate();
  const handleRemovePokemon = async (id: string) => {
    const updatedPokemons = pokemons.filter((pokemon) => pokemon.id !== id);
    const response = await DeletePokemon(id);
    if (response) {
      setPokemons(updatedPokemons);
      alert("Pokemon deletado com sucesso");
    }
  };

  const handleNavigateEditPage = (id: string) => {
    navigate("/edit/" + id);
  };

  useEffect(() => {
    const fetchPokemons = async () => {
      const response = await FetchPokemons();
      setPokemons(response);
    };
    fetchPokemons();
  }, []);

  return (
    <Container>
      {pokemons.length <= 0 && <Title>Não há pokemons cadastrados</Title>}
      <ContentContainer>
        {pokemons.map((pokemon) => {
          return (
            <PokemonCard
              pokemon={pokemon}
              key={pokemon.id}
              handleRemovePokemon={handleRemovePokemon}
              handleEditPokemon={handleNavigateEditPage}
            />
          );
        })}
      </ContentContainer>
    </Container>
  );
};

// pokedex-angular/src/app/homepage/homepage.component.ts
import { Component, OnInit } from '@angular/core';
import { PokemonService } from '../services/pokemonService'; // Importe seu serviço aqui
import { Router } from '@angular/router';

@Component({
  selector: 'app-homepage',
  templateUrl: './homepage.component.html',
  styleUrls: ['./homepage.component.css']
})
export class HomepageComponent implements OnInit {
  pokemons: any[] = [];
  constructor(private pokemonService: PokemonService, private router: Router) { }

  ngOnInit(): void {
    this.fetchPokemons();
  }

  async fetchPokemons() {
    try {
      this.pokemonService.fetchPokemons().subscribe({
        next: (response: any) => {
          this.pokemons = response;
        },
        error: (error: any) => {
          console.error(error);
        }
      });
    } catch (error) {
      console.error(error);
    }
  }


  async handleRemovePokemon(id: string) {
    try {
      const updatedPokemons = this.pokemons.filter(pokemon => pokemon.id !== id);
      this.pokemonService.deletePokemon(id).subscribe(() => {
        this.pokemons = updatedPokemons;
        alert('Pokemon deletado com sucesso');
      });
    } catch (error) {
      console.error(error);
    }
  }

  handleNavigateEditPage(id: string) {
    this.router.navigate(['/edit', id]);
  }
}

<div class="container">
  <ng-container *ngIf="pokemons.length <= 0; else pokemonList">
    <h2>Não há pokemons cadastrados</h2>
  </ng-container>
  <ng-template #pokemonList>
    <div class="content-container">
      <div *ngFor="let pokemon of pokemons">
        <app-pokemon-card
          [pokemon]="pokemon"
          (handleRemovePokemon)="handleRemovePokemon(pokemon.id)"
          (handleEditPokemon)="handleNavigateEditPage(pokemon.id)"
        ></app-pokemon-card>
      </div>
    </div>
  </ng-template>
</div>
