// pokedex-react/src/Components/Header/index.tsx
import { Container, Logo, Navbar, NavbarItem } from "./styles";
import AppLogo from "../../assets/pokedex_logo.png";
import { useNavigate } from "react-router-dom";
export const Header = () => {
  const navigate = useNavigate();
  return (
    <Container>
      <Logo src={AppLogo} />
      <Navbar>
        <NavbarItem onClick={() => navigate("/")}>Listar</NavbarItem>
        <NavbarItem onClick={() => navigate("/newPokemon")}>Incluir</NavbarItem>
      </Navbar>
    </Container>
  );
};

// pokedex-angular/src/app/header/header.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent {

  constructor(private router: Router) { }

  navigate(route: string) {
    this.router.navigate([route]);
  }
}

<div class="container">
  <img src="../../assets/pokedex_logo.png" />
  <ul>
    <li (click)="navigate('')">Listar</li>
    <li (click)="navigate('register')">Incluir</li>
  </ul>
</div>
